batch_size: 64
epochs: 1000
learning_rate: 0.0002
noise_steps: 1000
beta_start: 0.0001
beta_end: 0.02
is_train: True
sample_count: 5
path_to_plot_file: './all_losses.png'
path_to_trained_model: ./models/model_overlap_48.pth